WITH MAX_FISH_LENGTH AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) as MAX_LENGTH
    FROM 
        FISH_INFO
    GROUP BY 
        FISH_TYPE
)

SELECT 
    FI.ID,
    FNI.FISH_NAME,
    FI.LENGTH
FROM FISH_INFO FI 
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN MAX_FISH_LENGTH MFL 
    ON FI.FISH_TYPE = MFL.FISH_TYPE 
    AND FI.LENGTH = MFL.MAX_LENGTH
ORDER BY 
    FI.ID ASC;