-- HR_DEPARTMENT, HR_EMPLOYEES, HR_GRADE 테이블에서 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회하려 합니다. 
-- 2022년도의 평가 점수는 상,하반기 점수의 합을 의미하고, 평가 점수를 나타내는 컬럼의 이름은 SCORE

SELECT SUM(HG.SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME,	HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES AS HE
JOIN HR_DEPARTMENT AS HD ON HD.DEPT_ID = HE.DEPT_ID
JOIN HR_GRADE AS HG ON HE.EMP_NO = HG.EMP_NO
GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1; 
