WITH MAX_VIEWS AS (
    SELECT MAX(VIEWS) AS MAX_VIEWS
    FROM USED_GOODS_BOARD
)

SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_FILE UGF ON UGB.BOARD_ID = UGF.BOARD_ID
JOIN MAX_VIEWS MV ON UGB.VIEWS = MV.MAX_VIEWS
ORDER BY UGF.FILE_ID DESC;